import 'package:flutter/foundation.dart';
import '../models/report.dart';
import '../services/firebase_service.dart';

/// Provider for managing report submissions.
class ReportsProvider extends ChangeNotifier {
  final FirebaseService _firebaseService = FirebaseService();

  bool _isSubmitting = false;
  String? _errorMessage;

  bool get isSubmitting => _isSubmitting;
  String? get errorMessage => _errorMessage;

  /// Submit a new report
  Future<bool> submitReport({
    required String reportedItemId,
    required String reportedItemType,
    required String reportedItemTitle,
    required String reportedBy,
    String? reportedByName,
    required String reason,
    String? additionalDetails,
  }) async {
    _isSubmitting = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final report = ReportModel(
        id: '', // Generated by Firestore
        reportedItemId: reportedItemId,
        reportedItemType: reportedItemType,
        reportedItemTitle: reportedItemTitle,
        reportedBy: reportedBy,
        reportedByName: reportedByName,
        reason: reason,
        additionalDetails: additionalDetails,
        status: 'pending',
        createdAt: DateTime.now(),
      );

      await _firebaseService.submitReport(report);

      _isSubmitting = false;
      notifyListeners();
      return true;
    } catch (e) {
      _errorMessage = 'Failed to submit report: $e';
      _isSubmitting = false;
      notifyListeners();
      return false;
    }
  }

  void clearError() {
    _errorMessage = null;
    notifyListeners();
  }
}
