// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmjI1sdO0zEiEJbquE-d-F4FsvTf6aD1Q',
    appId: '1:51615689842:web:bc14a9e7c6b781d1caa6eb',
    messagingSenderId: '51615689842',
    projectId: 'barangaylink-eccd8',
    authDomain: 'barangaylink-eccd8.firebaseapp.com',
    storageBucket: 'barangaylink-eccd8.firebasestorage.app',
    measurementId: 'G-SCG1G7HF1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdRQpwuZZmWGjPxJBNem0SM7zzbM1zfps',
    appId: '1:51615689842:android:c7aaeaf387fbfcabcaa6eb',
    messagingSenderId: '51615689842',
    projectId: 'barangaylink-eccd8',
    storageBucket: 'barangaylink-eccd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0KoDAv-BWkefg3U8-sG8OmDVkR9s1nE',
    appId: '1:51615689842:ios:294aa558fc2d3dcbcaa6eb',
    messagingSenderId: '51615689842',
    projectId: 'barangaylink-eccd8',
    storageBucket: 'barangaylink-eccd8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0KoDAv-BWkefg3U8-sG8OmDVkR9s1nE',
    appId: '1:51615689842:ios:294aa558fc2d3dcbcaa6eb',
    messagingSenderId: '51615689842',
    projectId: 'barangaylink-eccd8',
    storageBucket: 'barangaylink-eccd8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmjI1sdO0zEiEJbquE-d-F4FsvTf6aD1Q',
    appId: '1:51615689842:web:27b3ee496dd4cf6dcaa6eb',
    messagingSenderId: '51615689842',
    projectId: 'barangaylink-eccd8',
    authDomain: 'barangaylink-eccd8.firebaseapp.com',
    storageBucket: 'barangaylink-eccd8.firebasestorage.app',
    measurementId: 'G-Z2W36B4SV4',
  );
}
