import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:google_fonts/google_fonts.dart';
import 'constants/app_constants.dart'; // Relative import
import 'providers/user_provider.dart'; // Relative import
import 'providers/barangay_provider.dart'; // Relative import
import 'providers/jobs_provider.dart'; // Phase 3: Jobs Provider
import 'providers/services_provider.dart'; // Phase 4: Services Provider
import 'providers/rentals_provider.dart'; // Phase 5: Rentals Provider
import 'providers/transaction_provider.dart'; // Phase 6: Transaction Provider
import 'providers/feedback_provider.dart'; // Phase 7: Feedback Provider
import 'providers/admin_provider.dart'; // Phase 8: Admin Provider
import 'providers/notification_provider.dart'; // Phase 9: Notification Provider
import 'providers/favorites_provider.dart'; // Phase 10: Favorites Provider
import 'package:flutter_application_1/screens/auth_gate.dart'; // Correct path to AuthGate
import 'firebase_options.dart'; // This is auto-generated by FlutterFire

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => UserProvider()),
        ChangeNotifierProvider(create: (_) => BarangayProvider()),
        ChangeNotifierProvider(create: (_) => JobsProvider()), // Phase 3
        ChangeNotifierProvider(create: (_) => ServicesProvider()), // Phase 4
        ChangeNotifierProvider(create: (_) => RentalsProvider()), // Phase 5
        ChangeNotifierProvider(create: (_) => TransactionProvider()), // Phase 6
        ChangeNotifierProvider(create: (_) => FeedbackProvider()), // Phase 7
        ChangeNotifierProvider(create: (_) => AdminProvider()), // Phase 8
        ChangeNotifierProvider(
          create: (_) => NotificationProvider(),
        ), // Phase 9
        ChangeNotifierProvider(create: (_) => FavoritesProvider()), // Phase 10
      ],
      child: MaterialApp(
        title: 'BarangayLink',
        debugShowCheckedModeBanner: false,

        // Modern Material 3 Theme Setup
        theme: ThemeData(
          useMaterial3: true,
          scaffoldBackgroundColor: kBackgroundColor,
          colorScheme: ColorScheme.fromSeed(
            seedColor: kPrimaryColor,
            primary: kPrimaryColor,
            secondary: kSecondaryColor,
            tertiary: kAccentColor,
            surface: kSurfaceColor,
            error: kErrorColor,
            brightness: Brightness.light,
          ),

          // Typography
          textTheme: GoogleFonts.poppinsTextTheme(),

          // Global AppBar Theme
          appBarTheme: AppBarTheme(
            backgroundColor: kSurfaceColor,
            foregroundColor: kTextPrimary,
            centerTitle: true,
            elevation: 0,
            scrolledUnderElevation: 0,
            titleTextStyle: GoogleFonts.poppins(
              color: kTextPrimary,
              fontSize: 18,
              fontWeight: FontWeight.w600,
            ),
            iconTheme: const IconThemeData(color: kTextPrimary),
          ),

          // Global Button Theme
          elevatedButtonTheme: ElevatedButtonThemeData(
            style: ElevatedButton.styleFrom(
              backgroundColor: kPrimaryColor,
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(vertical: 16),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          ),

          // Global Input Decoration (Text Fields)
          inputDecorationTheme: InputDecorationTheme(
            filled: true,
            fillColor: Colors.grey[50],
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8.0),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8.0),
              borderSide: BorderSide(color: Colors.grey.shade300),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8.0),
              borderSide: const BorderSide(color: kPrimaryColor, width: 2.0),
            ),
            labelStyle: const TextStyle(color: Colors.grey),
          ),
        ),

        home: const AuthGate(),
      ),
    );
  }
}
